- hosts: servers
  sudo: yes
  roles:
      - { role: bootstrap }
      - { role: bitsnpieces }
      - { role: chat, when: chat | default(False) }
      - { role: taskserver, when: task_server | default(False) }
