###
- name: Create A Records
  local_action:
      module: rax_dns_record
      api_key: "{{ rax_api_key }}"
      username: "{{ rax_user }}"
      domain: "{{ item.name.split('.')[1] + '.' + item.name.split('.')[2] }}"
      name: "{{ item.name }}"
      data: "{{ item.rax_accessipv4 }}"
      type: A
      state: present
  register: a_record
  with_items: rax.instances
  when: rax | default(False)
  tags: [ 'dns', 'a_record' ]
