###
- name: Provision instance
  local_action:
      module: rax
      api_key: "{{ rax_api_key }}"
      username: "{{ rax_user }}"
      name: "{{ rax_instance_name }}"
      flavor: "{{ rax_instance_flavor }}"
      image: "{{ rax_instance_image }}"
      region: "{{ rax_instance_region }}"
      key_name: "{{ rax_instance_key }}"
      auto_increment: "{{ 'Yes' if rax_instance_count|default(1) > 1 else 'No' }}"
      group: "{{ rax_instance_group | default('DEFAULT') }}"
      count: "{{ rax_instance_count | default(1) }}"
      user_data: "{{ rax_instance_user_data | default(False) }}"
      state: present
      wait: yes
  register: rax
  tags: [ 'rax', 'rax_provision' ]

- name: Rax Server
  debug: msg="{{ item.name }} @ {{ item.rax_accessipv4 }}"
  with_items: rax.instances
  tags: [ 'rax', 'rax_provision' ]
