---
- name: Install IRSSI
  yum: name=irssi state=present
  sudo: yes
  tags: [ 'chat', 'irssi' ]

- name: Deploy IRSSI Configuration
  copy:
    src=irssi/
    dest=/home/{{ user_name }}/.irssi/
    group={{ user_name }}
    owner={{ user_name }}
  sudo_user: "{{ user_name }}"
  tags: [ 'chat', 'irssi', 'irssi-config' ]

