---
- name: Enable Services
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items: "{{ firewall_services|default(false) }}"
  when: firewall_services|default(false)
  register: firewall_service
  failed_when: '"connect" not in firewall_port.msg'
  notify:
    - restart firewalld
  sudo: yes
  tags: [ 'firewalld', 'firewalld-service' ]

- name: Enable Ports
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items: "{{ firewall_ports|default(false) }}"
  when: firewall_ports|default(false)
  register: firewall_port
  failed_when: '"connect" not in firewall_port.msg'
  notify:
    - restart firewalld
  sudo: yes
  tags: [ 'firewalld', 'firewalld-ports' ]
