---
- name: test - apply role
  hosts: all
  
  roles:
    - .
  
  post_tasks:
    - name: tests - wait for startup
      pause:
        seconds: 10
        prompt: "Waiting for taskwarrior to start!"

    - name: tests - check port is listening
      command: netstat -antpd | grep -i taskd
      register:  netstat_out
      ignore_errors: yes
      sudo: yes

    - name: tests - assert taskd is listening
      assert:
        that: "{{ netstat_out | success }}"
